// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBHAkIs4qHoRLxqALHO4EKVePb75ERtg',
    appId: '1:799890236123:web:5a7bbde0c921c21182a2fe',
    messagingSenderId: '799890236123',
    projectId: 'test-app-development-6d9c9',
    authDomain: 'test-app-development-6d9c9.firebaseapp.com',
    storageBucket: 'test-app-development-6d9c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_iTvtzNy_0jS07YpYZj_Wel1x3HjD8ko',
    appId: '1:799890236123:android:54df3ace2f3f2f3f82a2fe',
    messagingSenderId: '799890236123',
    projectId: 'test-app-development-6d9c9',
    storageBucket: 'test-app-development-6d9c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6CCY68VX1szWlSM8xm7hrY81FFXa5WeI',
    appId: '1:799890236123:ios:1055b7d84db734ac82a2fe',
    messagingSenderId: '799890236123',
    projectId: 'test-app-development-6d9c9',
    storageBucket: 'test-app-development-6d9c9.appspot.com',
    iosBundleId: 'com.example.testProject1234.dev',
  );
}
