// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgKSWlhOj841x0UgwACV6LwoZO5r6-Ec',
    appId: '1:795333874803:web:ef09a4a2dc2b3ddf11c606',
    messagingSenderId: '795333874803',
    projectId: 'test-app-staging-f51e9',
    authDomain: 'test-app-staging-f51e9.firebaseapp.com',
    storageBucket: 'test-app-staging-f51e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAi3IMum19UBh2RfsssO-X4zSuHqxA5kk',
    appId: '1:795333874803:android:b10e8b964699c8f011c606',
    messagingSenderId: '795333874803',
    projectId: 'test-app-staging-f51e9',
    storageBucket: 'test-app-staging-f51e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGZCyVH2zvdOebKYjvLzehViA1E1LXPY',
    appId: '1:795333874803:ios:b06d8010dd548a4c11c606',
    messagingSenderId: '795333874803',
    projectId: 'test-app-staging-f51e9',
    storageBucket: 'test-app-staging-f51e9.appspot.com',
    iosBundleId: 'com.example.testProject1234.stg',
  );
}
